ALTER TABLE produkt ADD user_id INT DEFAULT NULL;
ALTER TABLE produkt ADD CONSTRAINT FK_1B938EA5A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
CREATE INDEX IDX_1B938EA5A76ED395 ON produkt (user_id);