front:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /

common_user:
    resource: "@CommonUserBundle/Resources/config/routing.yml"
    prefix:   /
    
kalkulator_user:
    resource: "@KalkulatorUserBundle/Controller/"
    type:     annotation
    prefix:   /

#kalkulator_dash_board:
#    resource: "@KalkulatorDashBoardBundle/Controller/"
#    type:     annotation
#    prefix:   /
    
eduweb_training_annotations:
    resource: "@KalkulatorKalkulatorBundle/Resources/config/routing.yml"
    prefix:   /