CREATE TABLE posilek (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, INDEX IDX_F3DD853AA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE posilek_produkty (id INT AUTO_INCREMENT NOT NULL, produkt_id INT DEFAULT NULL, posilek_id INT DEFAULT NULL, gram SMALLINT NOT NULL, INDEX IDX_8A6A6F5C75F42D9B (produkt_id), INDEX IDX_8A6A6F5CF12B67E2 (posilek_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE posilek ADD CONSTRAINT FK_F3DD853AA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE posilek_produkty ADD CONSTRAINT FK_8A6A6F5C75F42D9B FOREIGN KEY (produkt_id) REFERENCES produkt (id) ON DELETE SET NULL;
ALTER TABLE posilek_produkty ADD CONSTRAINT FK_8A6A6F5CF12B67E2 FOREIGN KEY (posilek_id) REFERENCES posilek (id) ON DELETE CASCADE;
ALTER TABLE posilek ADD nazwa VARCHAR(255) NOT NULL;